//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JPSDR_AutoYUY2.rc
// 
#define IDD_JPSDR_COLORSPACECONVERT      951
#define IDC_BT709_IN                     9051
#define IDC_BT601_IN                     9052
#define IDC_SMPTE_240M_IN                9053
#define IDC_FCC_IN                       9054
#define IDC_FULL_RANGE_IN                9055
#define IDC_PREVIEW                      9056
#define IDC_MATRIX_GROUP_IN              9057
#define IDC_BT709_OUT                    9058
#define IDC_BT601_OUT                    9059
#define IDC_SMPTE_240M_OUT               9060
#define IDC_FCC_OUT                      9061
#define IDC_FULL_RANGE_OUT               9062
#define IDC_MATRIX_GROUP_OUT             9063

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        952
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         9064
#define _APS_NEXT_SYMED_VALUE           951
#endif
#endif
