//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by JPSDR_IVTC_Dialog.rc
//
#define IDD_JPSDR_IVTC                  301
#define IDC_PROGRESSIVE                 3000
#define IDC_TELECINE                    3001
#define IDC_OUTPUT_FILTER               3002
#define IDC_THRESHOLD_IVTC              3003
#define IDC_OUTPUT_TEXT                 3004
#define IDC_THRESHOLD_FILTER            3005
#define IDC_LINE_REMOVED                3006
#define IDC_INV_POLAR                   3007
#define IDC_FIRST_LAST                  3008
#define IDC_DEINTERLACE                 3009
#define IDC_SMART                       3010
#define IDC_STANDARD                    3011
#define IDC_IVTC_STATIC2                3012
#define IDC_BLEND                       3013
#define IDC_THRESHOLD_DEINTERLACE       3014
#define IDC_Z_MODE                      3015
#define IDC_MOTION_MAP                  3016
#define IDC_MANUAL_MODE                 3017
#define IDC_BILINEAR                    3018
#define IDC_TRILINEAR                   3019
#define IDC_IVTC_STATIC3                3020
#define IDC_FILENAME                    3021
#define IDC_BROWSE                      3022
#define IDC_Y_ONLY                      3023
#define IDC_IVTC_STATIC                 -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        302
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         3024
#define _APS_NEXT_SYMED_VALUE           301
#endif
#endif
