//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JPSDR_AutoYUY2.rc
// 
#define IDD_JPSDR_RGBCONVERT             851
#define IDC_BT709                        8051
#define IDC_BT601                        8052
#define IDC_SMPTE_240M                   8053
#define IDC_FCC                          8054
#define IDC_FULL_RANGE                   8055
#define IDC_PREVIEW                      8056
#define IDC_MATRIX_GROUP                 8057
#define IDC_AUTODETECT                   8058
#define IDC_OUTPUT_GROUP                 8059
#define IDC_OUTPUT_YV24                  8060
#define IDC_OUTPUT_YV16                  8061
#define IDC_OUTPUT_YUY2                  8062
#define IDC_OUTPUT_YV12                  8063

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        852
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         8058
#define _APS_NEXT_SYMED_VALUE           851
#endif
#endif
