// Filtres_JPSDR.cpp : définit les fonctions exportées pour l'application DLL.
//


#include "VideoFilterEntry.h"
#include "ThreadPoolInterface.h"

ThreadPoolInterface *poolInterface;

VDX_DECLARE_VIDEOFILTERS_BEGIN()
	poolInterface=ThreadPoolInterface::Init(8);
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_Deinterlace)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_Saturation)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_IVTC)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_IVTC_Manual)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_Field_Shift)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_BlurMotion)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_Median)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_WideScreen)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_AutoYUY2)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_ChromaShift)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_AddBorder)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_RemoveFrames)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_RGBConvert)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_ColorSpaceConvert)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_CCC)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_InterlaceMotion)
#ifndef _M_AMD64
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_VHS)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_VHS_II)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_VHS_III)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_Smart_Deinterlace)
	VDX_DECLARE_VIDEOFILTER(filterDef_JPSDR_DeinterlaceII)
#endif
VDX_DECLARE_VIDEOFILTERS_END()

VDX_DECLARE_VFMODULE()


